### ISSUE TITLE
Tracking limits and cancelling orders

### ISSUE THREAD

**Issue by cmarshak** [nsidc/NSIDC-Data-Access-Notebook#3]
Thank you for your notebooks in navigating the NSIDC API.

I am downloading a lot of data and am wondering if there are ways to:

1) Keep track of orders associated with my earthdata UID or a given token; if so, can I cancel previous orders?

2) Track rate limits and order limits. Right now, experimenting with your notebook to download lots of data, I have already exceeded the limits. The `async` requests are indefinitely pending and the `sync` requests output the message `Rejected request due to capacity limitations`.

**Comment by asteiker** [comment]
Hi @cmarshak ,

Unfortunately there's no way for you to cancel your own orders but the NSIDC Operations team is happy to do so on your behalf. If you'd like us to cancel the remaining orders that are still pending, let me know. At the time of this message it looks like you have about 49 remaining orders. If you included your email in the API request, you should still receive your orders via email. If you're finding that each individual order is taking a long time to process, you may want to consider increasing the wait time in the order loop just so that you're not getting the pending status response so frequently in the notebook. 

I'm sorry to hear that you're getting an error on the sync requests. There is a maximum of 10 concurrent requests allowed from a single user so this is likely the cause of that error. If you're getting this error without sending concurrent requests, please let me know and I can troubleshoot further (and please send me an example request so that I can attempt to reproduce).

Thanks for reporting these issues - happy to provide further guidance or refine the notebook based off of your feedback.

Thanks,
Amy

**Comment by cmarshak** [comment]
Thank you so much for your prompt response and explanations. I did not know about the concurrent request limit, but have changed my scripts accordingly.

I think my confusion was in part due to the maintenance which was slowing down my pipeline. So delighted the API is so easy with jupyter + python.

Will have more questions in the not too distant future. Thank you again.
